sudo: required

services:
  - docker

before_install:
  - docker build -t nraval1729/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nraval1729/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-100938634681"
  on:
    branch: master